#cake: 0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82
#bnb: 0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c
#busd: 0xe9e7cea3dedca5984780bafc599bd69add087d56
 
[Pair3]
#TXL - BNB
Token1 = 0x1ffd0b47127fdd4097e54521c9e2c7f0d66aafc5
Token2 = 0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c
AlertType = RiseUpTo
# RiseUpTo or DropTo or ChangeIsOver
Value = 0.0008
#Always, OneTime
Frequency = OneTime
AutoSwap = Sell
#Buy, Sell, or No
SlippageTolerance = 1
FlexibleSlippage = False
AmountInput = 20
#0: all
GasPrice = 8
# GWei = 0.000000001 BNB
Gas = 230000
TimeLimit = 600000
